# Configurations
title:            XR class
longtitle:        XR class
author:           Yawen Li
email:            yawen.li@telecom.fr
description: >
  XR reshapes the world.

Week 1: Introduction and History of VR
Week 2: VR Technology and Perception
Week 3: Input Devices and Interaction Techniques
Week 4: Design Processes and Guidelines in VR
Week 5-7: Augmented Reality (History, Technology, and Interaction)
Week 8: Current Research Topics in VR/AR
Week 9: Project Presentations

version:          1.0
gitbook_version:  3.2.3

url:              'https://xrceci.github.io'  # 使用你的 GitHub Pages 域名
baseurl:          '/ClassXR'  # 确保这里是你 GitHub 仓库的名字
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/XR class 2024

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - pages
  - others

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
